//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 期中專案
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SelectShopEntities : DbContext
    {
        public SelectShopEntities()
            : base("name=SelectShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bag> Bags { get; set; }
        public virtual DbSet<Box> Boxes { get; set; }
        public virtual DbSet<Card> Cards { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<GiftPackageStyle> GiftPackageStyles { get; set; }
        public virtual DbSet<MaterialColor> MaterialColors { get; set; }
        public virtual DbSet<packageMaterial> packageMaterials { get; set; }
        public virtual DbSet<tActive> tActives { get; set; }
        public virtual DbSet<tAgency> tAgencies { get; set; }
        public virtual DbSet<tAllPackage> tAllPackages { get; set; }
        public virtual DbSet<tAppraisal> tAppraisals { get; set; }
        public virtual DbSet<tCart> tCarts { get; set; }
        public virtual DbSet<tCategory> tCategories { get; set; }
        public virtual DbSet<tDepartment> tDepartments { get; set; }
        public virtual DbSet<tDistributor> tDistributors { get; set; }
        public virtual DbSet<tDistrict> tDistricts { get; set; }
        public virtual DbSet<tEmployee> tEmployees { get; set; }
        public virtual DbSet<tEnterprise> tEnterprises { get; set; }
        public virtual DbSet<tEventLog> tEventLogs { get; set; }
        public virtual DbSet<tKeyword> tKeywords { get; set; }
        public virtual DbSet<tLabel> tLabels { get; set; }
        public virtual DbSet<tMember> tMembers { get; set; }
        public virtual DbSet<tOrder> tOrders { get; set; }
        public virtual DbSet<tOrder_temp> tOrder_temp { get; set; }
        public virtual DbSet<tPackageWayDetail> tPackageWayDetails { get; set; }
        public virtual DbSet<tPay> tPays { get; set; }
        public virtual DbSet<tPayType> tPayTypes { get; set; }
        public virtual DbSet<tProduct> tProducts { get; set; }
        public virtual DbSet<tPurchase> tPurchases { get; set; }
        public virtual DbSet<tReview> tReviews { get; set; }
        public virtual DbSet<tSale> tSales { get; set; }
        public virtual DbSet<tStatu> tStatus { get; set; }
        public virtual DbSet<tSubCategory> tSubCategories { get; set; }
        public virtual DbSet<tCity> tCities { get; set; }
        public virtual DbSet<tProdAppearance> tProdAppearances { get; set; }
    }
}
