//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 期中專案
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAllPackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tAllPackage()
        {
            this.tPackageWayDetails = new HashSet<tPackageWayDetail>();
        }
    
        public int PackageID { get; set; }
        public string PackName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Picture { get; set; }
        public Nullable<int> PackageStyleID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> MaterialID { get; set; }
    
        public virtual GiftPackageStyle GiftPackageStyle { get; set; }
        public virtual packageMaterial packageMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPackageWayDetail> tPackageWayDetails { get; set; }
    }
}
