//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 期中專案
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tEmployee()
        {
            this.tEventLogs = new HashSet<tEventLog>();
        }
    
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Cellphone { get; set; }
        public string Address { get; set; }
        public string Birthday { get; set; }
        public string Password { get; set; }
        public string E_mail { get; set; }
        public byte[] EmployeePhoto { get; set; }
        public string OnBoardDate { get; set; }
        public Nullable<int> DepID { get; set; }
    
        public virtual tDepartment tDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tEventLog> tEventLogs { get; set; }
    }
}
