//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 期中專案
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLabel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tLabel()
        {
            this.tSales = new HashSet<tSale>();
        }
    
        public int LabelID { get; set; }
        public string LabelName { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public byte[] SupplierPhoto { get; set; }
    
        public virtual tProduct tProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSale> tSales { get; set; }
    }
}
