//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 期中專案
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tOrder()
        {
            this.tPackageWayDetails = new HashSet<tPackageWayDetail>();
            this.tPurchases = new HashSet<tPurchase>();
        }
    
        public int OrderID { get; set; }
        public string GUI { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> RecMemberID { get; set; }
        public Nullable<int> Shipping { get; set; }
    
        public virtual tMember tMember { get; set; }
        public virtual tStatu tStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPackageWayDetail> tPackageWayDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPurchase> tPurchases { get; set; }
    }
}
